import { StyleSheet } from 'react-native';

const shadow = {
  shadowColor: '#0F172A',
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.08,
  shadowRadius: 16,
  elevation: 6,
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FCF8F7' },
  header: {
    backgroundColor: '#007FFF',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingHorizontal: 20,
    paddingBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  backIconImage: { width: 18, height: 18, tintColor: '#fff', resizeMode: 'contain' },
  title: { fontSize: 28, fontWeight: '700', color: '#FFFFFF' },
  scrollView: { flex: 1 },
  contentContainer: { paddingHorizontal: 20, paddingVertical: 24, paddingBottom: 120 },
  settingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    ...shadow,
  },
  cardTextWrap: { flex: 1, paddingRight: 12 },
  label: { fontSize: 17, fontWeight: '700', color: '#111827', marginBottom: 4 },
  note: { fontSize: 14, color: '#6B7280', textAlign: 'left' },
  toggleButton: {
    width: 70,
    height: 34,
    borderRadius: 17,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  toggleOn: { backgroundColor: '#007FFF', justifyContent: 'space-between' },
  toggleOff: { backgroundColor: '#E5E7EB', justifyContent: 'space-between' },
  toggleLabel: { fontSize: 13, fontWeight: '700' },
  toggleLabelOn: { color: '#FFFFFF' },
  toggleLabelOff: { color: '#374151' },
  toggleCircle: { width: 22, height: 22, borderRadius: 11 },
  toggleCircleOn: { backgroundColor: '#FFFFFF', marginLeft: 6 },
  toggleCircleOff: { backgroundColor: '#FFFFFF', marginLeft: 6, borderWidth: 1, borderColor: '#D1D5DB' },
  voiceCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 20,
    marginTop: 4,
    ...shadow,
  },
  voiceTitle: { fontSize: 17, fontWeight: '700', color: '#111827' },
  voiceNote: { fontSize: 14, color: '#6B7280', marginTop: 4 },
  voiceDropdownWrap: { marginTop: 16 },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F6F8FB',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  dropdownButtonText: { fontSize: 16, fontWeight: '600', color: '#111827' },
  caret: { marginLeft: 12, color: '#6B7280', fontSize: 16 },
  dropdownMenu: {
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  dropdownItem: { paddingVertical: 14, paddingHorizontal: 18, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  dropdownItemLast: { borderBottomWidth: 0 },
  dropdownItemText: { fontSize: 16, color: '#111827' },
  fabContainer: { position: 'absolute', right: 24, bottom: 32 },
  fabSubmenu: { position: 'absolute', right: 0, bottom: 76, alignItems: 'flex-end' },
  fabSubmenuItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 190,
    ...shadow,
  },
  fabSubmenuIcon: { marginRight: 10, color: '#007FFF', fontSize: 18 },
  fabSubmenuImageSize: { width: 22, height: 14, tintColor: '#007FFF', resizeMode: 'contain' },
  fabSubmenuText: { fontWeight: '600', color: '#0F172A', flexShrink: 1 },
  fabMain: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#007FFF',
    justifyContent: 'center',
    alignItems: 'center',
    ...shadow,
  },
  fabMainIcon: { color: '#fff', fontSize: 26, fontWeight: '700' },
});
